### PR TITLE
Don't start interval if disabled #24

### PR DESCRIPTION
**Pull request by davedoesdev**

### CODE REVIEW

**Comment by torch2424** [comment]
@davedoesdev Sorry for not looking this over yet! Been visiting parents over the weekend! 👍

**Review by torch2424 — APPROVED** [review]

**Comment by torch2424** [comment]
@davedoesdev Thanks again for doing this! 😄

**Comment by torch2424** [comment]
Deployed in `1.2.1` 😄

**Comment by davedoesdev** [comment]
Thanks!

**Pull request merged**
